### ISSUE TITLE
Fails when the unique values of the input column include two values with nan or  None

### ISSUE THREAD

**Issue by KawaiRie1024** [sapientml/sapientml#58]
**Describe the bug**
Fails when the unique values of the input column include two values with nan or  None

**To Reproduce**
1. Show your code calling .

<details>
<summary> script </summary>

```python
import pandas as pd
import numpy as np
from sapientml import SapientML

df = pd.DataFrame({
    "A": list(range(1, 11)),
    "B": [None if i % 2 == 0 else "B" for i in range(1, 11)],
    # It also fails when the value np.nan is included.
    # "B": [np.nan if i % 2 == 0 else "B" for i in range(1, 11)],
    "y": ["y" if i % 2 == 0 else "n" for i in range(1, 11)]
})

sml = SapientML(
    ["y"],
    add_explanation = True,
)

sml.fit(df)
```
</details>

2. Attach the datasets or dataframes input to `generate_code()` if possible.
No datasets.

3. Show the generated code such as `1_default.py` when it was generated.
There is no bug in the generated code.

4. Show the messages of SapientML and/or generated code.

<details>
<summary> Traceback </summary>

```
Traceback (most recent call last):
  File "/workspace/SapientML/main_issue.py", line 17, in <module>
    sml.fit(df)
  File "/workspace/SapientML/venv/lib/python3.10/site-packages/sapientml/main.py", line 340, in fit
    self.generator.save(self.output_dir)
  File "/workspace/SapientML/venv/lib/python3.10/site-packages/sapientml_core/generator.py", line 422, in save
    self.add_explanation()
  File "/workspace/SapientML/venv/lib/python3.10/site-packages/sapientml_core/generator.py", line 426, in add_explanation
    explain(
  File "/workspace/SapientML/venv/lib/python3.10/site-packages/sapientml_core/explain/main.py", line 101, in process
    eda.check_consistency(convert=False)
  File "/workspace/SapientML/venv/lib/python3.10/site-packages/sapientml_core/explain/AutoEDA.py", line 288, in check_consistency
    self.df.data[key] = self.__convert_object(self.df.data[key], convert, key)
  File "/workspace/SapientML/venv/lib/python3.10/site-packages/sapientml_core/explain/AutoEDA.py", line 364, in __convert_object
    bool_check = self.__is_bool(unique_alpha)
  File "/workspace/SapientML/venv/lib/python3.10/site-packages/sapientml_core/explain/AutoEDA.py", line 298, in __is_bool
    sorted_unique_vals = sorted([_.lower().strip() for _ in unique_vals])
  File "/workspace/SapientML/venv/lib/python3.10/site-packages/sapientml_core/explain/AutoEDA.py", line 298, in <listcomp>
    sorted_unique_vals = sorted([_.lower().strip() for _ in unique_vals])
AttributeError: 'float' object has no attribute 'lower'
```
</details>

**Expected behavior**
Work when the case above.

**Environment (please complete the following information):**
 - sapientml                 0.4.9
 - sapientml-core            0.4.10
 - sapientml-loaddata        0.4.2
 - sapientml-preprocess      0.3.5

**Comment by arima-tsukasa** [comment]
I ran the script to reproduce and got the following Traceback:
The issue error does not currently occur.

```
Traceback (most recent call last):
  File "c:\Users\xxxxx\.vscode\extensions\ms-python.python-2024.0.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 3489, in <module>
    main()
  File "c:\Users\xxxxx\.vscode\extensions\ms-python.python-2024.0.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 3482, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "c:\Users\xxxxx\.vscode\extensions\ms-python.python-2024.0.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 2510, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "c:\Users\xxxxx\.vscode\extensions\ms-python.python-2024.0.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 2517, in _exec
    globals = pydevd_runpy.run_path(file, globals, '__main__')
  File "c:\Users\xxxxx\.vscode\extensions\ms-python.python-2024.0.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\Users\xxxxx\.vscode\extensions\ms-python.python-2024.0.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\xxxxx\.vscode\extensions\ms-python.python-2024.0.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxxxx\AppData\Local\Temp\tmpl4pnd0xf\final_train.py", line 15, in <module>
    train_dataset[STRING_COLS_WITH_MISSING_VALUES] = simple_imputer.fit_transform(train_dataset[STRING_COLS_WITH_MISSING_VALUES])
  File "C:\work\workspace\sapientml_tashirovenv\lib\site-packages\sklearn\utils\_set_output.py", line 157, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "C:\work\workspace\sapientml_tashirovenv\lib\site-packages\sklearn\base.py", line 916, in fit_transform    
    return self.fit(X, **fit_params).transform(X)
  File "C:\work\workspace\sapientml_tashirovenv\lib\site-packages\sklearn\base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\work\workspace\sapientml_tashirovenv\lib\site-packages\sklearn\impute\_base.py", line 408, in fit      
    self.statistics_ = self._dense_fit(
  File "C:\work\workspace\sapientml_tashirovenv\lib\site-packages\sklearn\impute\_base.py", line 504, in _dense_fit    most_frequent[i] = _most_frequent(row, np.nan, 0)
  File "C:\work\workspace\sapientml_tashirovenv\lib\site-packages\sklearn\impute\_base.py", line 46, in _most_frequent
    most_frequent_value = min(
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```
-> Error running final_train.py

The problem areas in final_train.py are:

```python
# PREPROCESSING-1
import numpy as np
from sklearn.impute import SimpleImputer
STRING_COLS_WITH_MISSING_VALUES = ['B']
simple_imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
train_dataset[STRING_COLS_WITH_MISSING_VALUES] = simple_imputer.fit_transform(train_dataset[STRING_COLS_WITH_MISSING_VALUES])
with open('simpleimputer-string.pkl', 'wb') as f:
    pickle.dump(simple_imputer, f)
```

Similar code is used in the candidate script (x_script.py).
I investigated why there was no problem there.

### results of the survey

- Why doesn't the final_train.py error occur in the candidate script?

The problem occurs in the process of finding the most frequent value to fill in the missing data.

```python
simple_imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
train_dataset[NUMERIC_COLS_WITH_MISSING_VALUES] = simple_imputer.fit_transform(train_dataset[NUMERIC_COLS_WITH_MISSING_VALUES])
```

#### Cause of the problem
The cause of the problem is that there are at least two types of data with the highest number of occurrences in the same number, and the candidate contains None.
When the number of occurrences is the same, min is used to adopt the beginning in ascending order. If None (NoneType) and all other types are mixed and the min argument is specified, an error occurs.

In the case of the candidate script, there was one type of data that had a high number of occurrences due to data splitting.
Therefore, the problem did not occur.
['B',None,'B',None,'B']

- What about np.nan instead of None?

```python
SimpleImputer(missing_values=np.nan, strategy='most_frequent')
```

The values specified for missing_values in SimpleImputer are excluded from the candidates because of the values to be replaced. Therefore, there is no problem.

- How to handle missing values when read with read_ csv? (Will it be None?)

The missing value is np.nan.

### Conclusion and how to deal with it

None appears in the data only when you manually create a dataframe and intentionally include None.
Therefore, I'm guessing that the problem can be solved by adding a process to replace None with np.nan before the process of converting missing values in SimpleInputer.
