### ISSUE TITLE
Scripts generated with `generatedcode` fail with shap.Explainer.

### ISSUE THREAD

**Issue by arima-tsukasa** [sapientml/sapientml#67]
**Describe the bug**
Scripts generated with `generatedcode` fail with shap.Explainer.

**To Reproduce**
1. Run the following test code:
```bash
poetry run -- pytest -p no:warnings -s tests/sapientml/test_generatedcode.py::test_regressor_works_with_nosparse
```

<details>
<summary> generated code </summary>

```python
# *** GENERATED PIPELINE ***

# LOAD DATA
import pandas as pd
train_dataset = pd.read_csv(r"/home/xxxxx/Fujitsu_AutoML_OSS/sapientml/tests/fixtures/datasets/testdata_df.csv", encoding="UTF-8", delimiter=",")

# TRAIN-TEST SPLIT
from sklearn.model_selection import train_test_split
def split_dataset(dataset, train_size=0.75, random_state=17):
    train_dataset, test_dataset = train_test_split(dataset, train_size=train_size, random_state=random_state)
    return train_dataset, test_dataset	
train_dataset, test_dataset = split_dataset(train_dataset)

# DROP IGNORED COLUMNS
ignore_columns = ['explanatory_text_english', 'explanatory_text_japanese', 'explanatory_json', 'explanatory_list']
train_dataset = train_dataset.drop(ignore_columns, axis=1, errors="ignore")
test_dataset = test_dataset.drop(ignore_columns, axis=1, errors="ignore")

# Remove special symbols that interfere with visualization and model training
import re
cols_has_symbols = ['columns_symbol年月日,:<{}[]"\'\\']
inhibited_symbol_pattern = re.compile(r"[\{\}\[\]\",:<'\\]+")
train_dataset = train_dataset.rename(columns=lambda col: inhibited_symbol_pattern.sub("", col) if col in cols_has_symbols else col)
test_dataset = test_dataset.rename(columns=lambda col: inhibited_symbol_pattern.sub("", col) if col in cols_has_symbols else col)

# HANDLE MIXED TYPE
import numpy as np
cols_numeric_and_string = ['explanatory_number_string', 'explanatory_mixed_type', 'explanatory_mixed_type_has_nan']
for col in cols_numeric_and_string:
    train_dataset[col + '__str'] = np.where(pd.to_numeric(train_dataset[col], errors='coerce').isnull(), train_dataset[col], np.nan)
    train_dataset[col + '__num'] = np.where(pd.to_numeric(train_dataset[col], errors='coerce').isnull(), np.nan, train_dataset[col]).astype(float)
    train_dataset = train_dataset.drop(col, axis=1)
    test_dataset[col + '__str'] = np.where(pd.to_numeric(test_dataset[col], errors='coerce').isnull(), test_dataset[col], np.nan)
    test_dataset[col + '__num'] = np.where(pd.to_numeric(test_dataset[col], errors='coerce').isnull(), np.nan, test_dataset[col]).astype(float)
    test_dataset = test_dataset.drop(col, axis=1)

# CONVERT INF TO NAN
import numpy as np
cols_inf_values = ['target_number_has_inf', 'explanatory_has_inf']
train_dataset[cols_inf_values] = train_dataset[cols_inf_values].replace([-np.inf, np.inf], np.nan)
test_dataset[cols_inf_values] = test_dataset[cols_inf_values].replace([-np.inf, np.inf], np.nan)

# DISCARD COLUMNS WITH ONE VALUE ONLY
cols_one_value_only = ['explanatory_all_missing']
train_dataset = train_dataset.drop(cols_one_value_only, axis=1, errors="ignore")
test_dataset = test_dataset.drop(cols_one_value_only, axis=1, errors="ignore")


# DISCARD IRRELEVANT COLUMNS
irrelevant_columns = ['explanatory_str_other']
train_dataset = train_dataset.drop(irrelevant_columns, axis=1, errors="ignore")
test_dataset = test_dataset.drop(irrelevant_columns, axis=1, errors="ignore")

# PREPROCESSING-1
# Component: Preprocess:SimpleImputer
# Efficient Cause: Preprocess:SimpleImputer is required in this pipeline since the dataset has ['feature:missing_values_presence']. The relevant features are: ['explanatory_cate_almost_missing', 'explanatory_cate_has_nan', 'explanatory_has_inf', 'explanatory_mixed_type__num', 'explanatory_mixed_type__str', 'explanatory_mixed_type_has_nan__num', 'explanatory_mixed_type_has_nan__str', 'explanatory_num_almost_missing', 'explanatory_num_has_nan', 'explanatory_number_string__num', 'explanatory_number_string__str', 'target_category_binary_has_nan', 'target_number_has_inf', 'target_number_has_nan'].
# Purpose: Imputation transformer for completing missing values
# Form:
#   Input: array of shape (n_features,)
#   Key hyperparameters used: 
#		 "missing_values: int, float, str, np.nan or None, default=np.nan" :: The placeholder for the missing values. All occurrences of missing_values will be imputed. For pandas’ dataframes with nullable integer dtypes with missing values, missing_values should be set to np.nan, since pd.NA will be converted to np.nan.
#		 "strategy: str, default='mean'" :: The imputation strategy. If "mean", then replace missing values using the mean along each column. Can only be used with numeric data. If "most_frequent", then replace missing using the most frequent value along each column. Can be used with strings or numeric data. If there is more than one such value, only the smallest is returned.
# Alternatives: Although  can also be used for this dataset, Preprocess:SimpleImputer is used because it has more  than .
# Order: Preprocess:SimpleImputer should be applied  
import numpy as np
from sklearn.impute import SimpleImputer
NUMERIC_COLS_WITH_MISSING_VALUES = ['explanatory_has_inf', 'explanatory_mixed_type__num', 'explanatory_mixed_type_has_nan__num', 'explanatory_num_has_nan', 'explanatory_number_string__num', 'target_number_has_inf', 'target_number_has_nan']
simple_imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
train_dataset[NUMERIC_COLS_WITH_MISSING_VALUES] = simple_imputer.fit_transform(train_dataset[NUMERIC_COLS_WITH_MISSING_VALUES])
test_dataset[NUMERIC_COLS_WITH_MISSING_VALUES] = simple_imputer.transform(test_dataset[NUMERIC_COLS_WITH_MISSING_VALUES])
NUMERIC_ALMOST_MISSING_COLS = ['explanatory_num_almost_missing']
train_dataset[NUMERIC_ALMOST_MISSING_COLS] = train_dataset[NUMERIC_ALMOST_MISSING_COLS].fillna(0)
test_dataset[NUMERIC_ALMOST_MISSING_COLS] = test_dataset[NUMERIC_ALMOST_MISSING_COLS].fillna(0)

# PREPROCESSING-2
import numpy as np
from sklearn.impute import SimpleImputer
STRING_COLS_WITH_MISSING_VALUES = ['explanatory_cate_has_nan', 'target_category_binary_has_nan']
simple_imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
train_dataset[STRING_COLS_WITH_MISSING_VALUES] = simple_imputer.fit_transform(train_dataset[STRING_COLS_WITH_MISSING_VALUES])
test_dataset[STRING_COLS_WITH_MISSING_VALUES] = simple_imputer.transform(test_dataset[STRING_COLS_WITH_MISSING_VALUES])
STRING_ALMOST_MISSING_COLS = ['explanatory_cate_almost_missing', 'explanatory_mixed_type__str', 'explanatory_mixed_type_has_nan__str', 'explanatory_number_string__str']
train_dataset[STRING_ALMOST_MISSING_COLS] = train_dataset[STRING_ALMOST_MISSING_COLS].astype(str)
test_dataset[STRING_ALMOST_MISSING_COLS] = test_dataset[STRING_ALMOST_MISSING_COLS].astype(str)
train_dataset[STRING_ALMOST_MISSING_COLS] = train_dataset[STRING_ALMOST_MISSING_COLS].fillna('')
test_dataset[STRING_ALMOST_MISSING_COLS] = test_dataset[STRING_ALMOST_MISSING_COLS].fillna('')

# PREPROCESSING-3
# Component: Preprocess:OrdinalEncoder
# Efficient Cause: Preprocess:OrdinalEncoder is required in this pipeline since the dataset has ['feature:str_category_presence', 'feature:str_category_small_presence', 'feature:str_category_binary_presence']. The relevant features are: ['target_category_binary_nonnum', 'target_category_multi_nonnum', 'target_category_binary_has_nan', 'target_category_binary_has_japanese', 'explanatory_binary_category_nonnum', 'explanatory_multi_category_nonnum', 'explanatory_cate_has_nan', 'explanatory_multi_category_large', 'explanatory_cate_almost_missing', 'explanatory_has_japanese', 'explanatory_number_string__str', 'explanatory_mixed_type__str', 'explanatory_mixed_type_has_nan__str'].
# Purpose: Encode categorical features as an integer array
# Form:
#   Input: list of arrays
#   Key hyperparameters used: 
#		 "handle_unknown: {'error', 'use_encoded_value'}, default='error'" :: When set to ‘error’ an error will be raised in case an unknown categorical feature is present during transform. When set to ‘use_encoded_value’, the encoded value of unknown categories will be set to the value given for the parameter unknown_value. In inverse_transform, an unknown category will be denoted as None.
#		 "unknown_value: int or np.nan, default=None" :: When the parameter handle_unknown is set to ‘use_encoded_value’, this parameter is required and will set the encoded value of unknown categories. It has to be distinct from the values used to encode any of the categories in fit. If set to np.nan, the dtype parameter must be a float dtype.
# Alternatives: Although [Preprocess:OneHotEncoder] can also be used for this dataset, Preprocess:OrdinalEncoder is used because it has more feature:str_category_small_presence than feature:str_category_binary_presence.
# Order: Preprocess:OrdinalEncoder should be applied  
from sklearn.preprocessing import OrdinalEncoder
CATEGORICAL_COLS = ['explanatory_binary_category_nonnum', 'explanatory_cate_almost_missing', 'explanatory_cate_has_nan', 'explanatory_has_japanese', 'explanatory_mixed_type__str', 'explanatory_mixed_type_has_nan__str', 'explanatory_multi_category_large', 'explanatory_multi_category_nonnum', 'explanatory_number_string__str', 'target_category_binary_has_japanese', 'target_category_binary_has_nan', 'target_category_binary_nonnum', 'target_category_multi_nonnum']
ordinal_encoder = OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1)
train_dataset[CATEGORICAL_COLS] = ordinal_encoder.fit_transform(train_dataset[CATEGORICAL_COLS])
test_dataset[CATEGORICAL_COLS] = ordinal_encoder.transform(test_dataset[CATEGORICAL_COLS])

# PREPROCESSING-4
# Component: Preprocess:DateTime
# Efficient Cause: Preprocess:DateTime is required in this pipeline since the dataset has ['feature:str_date_presence']. The relevant features are: ['explanatory_datetime'].
# Purpose: Convert argument to datetime.
# Form:
#   Input: scalar, array-like, Series or DataFrame/dict-like
#   Key hyperparameters used: 
#		 "errors: {‘ignore’, ‘raise’, ‘coerce’}, default ‘raise’" :: If 'coerce', then invalid parsing will be set as NaT.
# Alternatives: Although  can also be used for this dataset, Preprocess:DateTime is used because it has more  than .
# Order: Preprocess:DateTime should be applied  
DATE_COLUMNS = ['explanatory_datetime']
for _col in DATE_COLUMNS:
    train_date_col = pd.to_datetime(train_dataset[_col], errors='coerce')
    train_dataset[_col + "_year"] = train_date_col.dt.year.fillna(-1)
    train_dataset[_col + "_month"] = train_date_col.dt.month.fillna(-1)
    train_dataset[_col + "_day"] = train_date_col.dt.day.fillna(-1)
    train_dataset[_col + "_day_of_week"] = train_date_col.dt.dayofweek.fillna(-1)
    train_dataset.drop(_col, axis=1, inplace=True)
    
    test_date_col = pd.to_datetime(test_dataset[_col], errors='coerce')
    test_dataset[_col+ "_year"] = test_date_col.dt.year.fillna(-1)
    test_dataset[_col + "_month"] = test_date_col.dt.month.fillna(-1)
    test_dataset[_col + "_day"] = test_date_col.dt.day.fillna(-1)
    test_dataset[_col + "_day_of_week"] = test_date_col.dt.dayofweek.fillna(-1)
    test_dataset.drop(_col, axis=1, inplace=True)

# DETACH TARGET
TARGET_COLUMNS = ['target_number']
feature_train = train_dataset.drop(TARGET_COLUMNS, axis=1)
target_train = train_dataset[TARGET_COLUMNS].copy()
if set(TARGET_COLUMNS).issubset(test_dataset.columns.tolist()):
    feature_test = test_dataset.drop(TARGET_COLUMNS, axis=1)
    target_test = test_dataset[TARGET_COLUMNS].copy()
else:
    feature_test = test_dataset

# MODEL
import numpy as np
from xgboost import XGBRegressor
random_state_model = 42
model = XGBRegressor(random_state=random_state_model, )
model.fit(feature_train, target_train.values.ravel())
y_pred = model.predict(feature_test)

#EVALUATION
if set(TARGET_COLUMNS).issubset(test_dataset.columns.tolist()):
    from sklearn.metrics import mean_absolute_error
    mae = mean_absolute_error(target_test, y_pred)
    print('RESULT: MAE:', str(mae))


# OUTPUT PREDICTION
prediction = pd.DataFrame(y_pred, columns=TARGET_COLUMNS, index=feature_test.index)
prediction.to_csv("./prediction_result.csv")

# PERMUTATION IMPORTANCE
from sklearn.inspection import permutation_importance
if len(feature_train.columns) <= 100:
    perm = permutation_importance(model, feature_train, target_train[TARGET_COLUMNS[0]],
                                    n_repeats=5,
                                    random_state=0)
    perm_df = pd.DataFrame({"feature": feature_train.columns, "importance": perm.importances_mean})
    perm_df.to_csv("./permutation_importance.csv", index=False)


# Models are restricted because of execution time.
models_for_shap = ['XGBClassifier', 'XGBRegressor', 'LGBMClassifier', 'LGBMRegressor', 'GradientBoostingClassifier', 'GradientBoostingRegressor']
if model.__class__.__name__ in models_for_shap:
    import shap
    feature_shap = feature_train.sample(1000) if feature_train.shape[0] > 1000 else feature_train
    explainer = shap.Explainer(model, feature_shap)
    shap_values = explainer(feature_shap)
    # summarize the effects of all the features
    shap.plots.beeswarm(shap_values)
    #bar plots
    shap.plots.bar(shap_values)

```
</details>
<details>
<summary> Traceback </summary>

```python
Traceback (most recent call last):
  File "/home/xxxxx/code_test.py", line 175, in <module>
    explainer = shap.Explainer(model, feature_shap)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxxxx/Fujitsu_AutoML_OSS/venv_sapientml/lib/python3.11/site-packages/shap/explainers/_explainer.py", line 185, in __init__
    explainers.TreeExplainer.__init__(self, self.model, self.masker, link=self.link, feature_names=self.feature_names, linearize_link=linearize_link, **kwargs)
  File "/home/xxxxx/Fujitsu_AutoML_OSS/venv_sapientml/lib/python3.11/site-packages/shap/explainers/_tree.py", line 166, in __init__
    self.model = TreeEnsemble(model, self.data, self.data_missing, model_output)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxxxx/Fujitsu_AutoML_OSS/venv_sapientml/lib/python3.11/site-packages/shap/explainers/_tree.py", line 998, in __init__
    self.trees = xgb_loader.get_trees(data=data, data_missing=data_missing)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxxxx/Fujitsu_AutoML_OSS/venv_sapientml/lib/python3.11/site-packages/shap/explainers/_tree.py", line 1783, in get_trees
    trees.append(SingleTree({
                 ^^^^^^^^^^^^
  File "/home/xxxxx/Fujitsu_AutoML_OSS/venv_sapientml/lib/python3.11/site-packages/shap/explainers/_tree.py", line 1609, in __init__
    _cext.dense_tree_update_weights(
TypeError: Cannot cast array data from dtype('O') to dtype('float64') according to the rule 'safe'
```
</details>

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - Python Version: [e.g. 3.11.1]
 - sapientml Version: [e.g. 0.4.10]
 - sapientml-core Version: [e.g. 0.5.0]

**Comment by AkiraUra** [comment]
Merged. Close.
